### ISSUE TITLE
Evaluate the log output at ManoController & ManoClient

### ISSUE THREAD

**Issue by kostistr** [openslice/io.openslice.mano#13]
Evaluate the logging output, as seen in the images below.

Necessary debug logging should be moved to the "debug" level, and any unnecessary logging should be deleted.

ManoController excess logging:
![image](https://github.com/openslice/io.openslice.mano/assets/16688199/772709fc-63ab-4f7c-b889-24c4bb7394b0)
![image](https://github.com/openslice/io.openslice.mano/assets/16688199/11dc6e3a-bcb0-4351-a59b-9c9e3b1ec448)
![image](https://github.com/openslice/io.openslice.mano/assets/16688199/f62c0553-4f98-4cb8-8e8a-93e5bdf6a617)

ManoClient excess logging:
![image](https://github.com/openslice/io.openslice.mano/assets/16688199/99ebeea7-2387-4b16-9f88-0ee04e2a81e2)
![image](https://github.com/openslice/io.openslice.mano/assets/16688199/fb7c3e5d-75de-46e6-b8dd-165855acc8d7)

**Comment by ctranoris** [comment]
Thank you so much for your recent update and the hard work you've put into addressing this issue. It’s always a pleasure to see the dedication and expertise you bring to the table. Your contribution has not only solved the problem at hand but has also enriched our codebase significantly. 🌟

The meticulous details you've provided in your closing comment are incredibly helpful, and they offer great insights into how the issue was resolved. This not only aids our current project but also serves as a valuable resource for future reference.

As you marked this issue as closed, I want to express our heartfelt appreciation for your commitment. Your ability to navigate through complex code and come up with efficient solutions is truly commendable.

Should you have any further insights or reflections on this issue or stumble upon new challenges, please know that your thoughts and contributions are always welcome. Your knack for problem-solving is a beacon for all of us, and we look forward to more of your valuable inputs.
